### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by TomerPacific** [TomerPacific/MediumArticleFetcher#23]
Some of the items on the website are not styled correctly (I.E. user profile image is too close the the input field).

**Comment by JohnG1985** [comment]
If some elements on a website are not styled correctly, it is likely that there is an issue with the website's CSS stylesheet. CSS (Cascading Style Sheets) is a language used to define the visual appearance of elements on a website, such as fonts, colors, and positioning.

To fix issues with the styling of elements on a website, you will need to inspect the website's CSS stylesheet and identify any issues with the styles that are applied to the affected elements. This may involve checking for any errors in the styles, such as incorrect selectors or incorrect values for style properties. You may also need to adjust the styles to ensure that they are applied correctly to the affected elements.

To inspect the CSS stylesheet for a website, you can use your web browser's developer tools. Most modern web browsers include developer tools that allow you to inspect and modify the HTML and CSS of a website in real-time. You can use these tools to view the styles that are applied to a particular element and make changes to the styles to see how they affect the appearance of the element.

Once you have identified and fixed any issues with the styles, you will need to save your changes and refresh the website to see the updated styles in action. If you are not able to fix the issues yourself, you may need to contact the website's administrator or the person who created the website for assistance.
